# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image: 
  repository: registry.spectest.jin.apirs.net/100007996/voting-vote
  tag: latest
  pullSecret: cfcr

redis:
  usePassword: false

replicaCount: 1
