# Default values for example-voting-app.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# Enabling postgres service, by default
postgresql:
  enabled: true
  # Uncomment line below and set to postgres host fqdn is using postgres outside release
  # postgresServer: postgres_host_fqdn
  postgresUser: postgres
  postgresPassword: postgres
  persistence:
    enabled: false

# Enabling redis service, by default
redis:
  enabled: true
  usePassword: false
  persistence:
    enabled: false
  podAnnotations:
    ars.axway.com/server-size: Medium

vote:
  host: result-2ff5c4dfa3d16e2401c1e55bfc579342.spectest.rganji.apirs.net
result:
  host: result-2ff5c4dfa3d16e2401c1e55bfc579342.spectest.rganji.apirs.net
